language: node_js
node_js:
  - '4.2'
  - '5.1'
  
sudo: true

before_install:
  # installing latest PHP with PHPBrew
  - sudo add-apt-repository ppa:ondrej/php5-oldstable
  - sudo apt-get update
  - sudo apt-get install -y php5-cli  
  # installing Selenium
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "selenium-standalone start >/dev/null 2>&1 &"
  - "php -S -t test/data/app 127.0.0.1:8000 &"

script: gulp test